### ISSUE TITLE
Rate Request Sample not working on Windows

### ISSUE THREAD

**Issue by iambrandontaylor** [gtaylor/python-fedex#10]
I registered for a developer account from FedEx and plugged all of my account information in to the config. I created a virtualenv with the latest version of fedex and suds installed via pip. I'm using Python 2.7.1 32-bit on Windows 7. When running the rate request sample, I'm getting an error:

Traceback (most recent call last):
  File "rate_request.py", line 20, in <module>
    rate_request = FedexRateServiceRequest(CONFIG_OBJ)
  File "C:\Users\brandon\Desktop\gtaylor-python-fedex-e5a26cc\fedex\services\rate_service.py", line 36, in __init__
    *args, **kwargs)
  File "C:\Users\brandon\Desktop\gtaylor-python-fedex-e5a26cc\fedex\base_service.py", line 84, in __init__
    self.client = Client('file://%s' % self.wsdl_path)
  File "C:\Users\brandon\python_virtualenvs\fedex_test\lib\site-packages\suds\client.py", line 112, in __init__
    self.wsdl = reader.open(url)
  File "C:\Users\brandon\python_virtualenvs\fedex_test\lib\site-packages\suds\reader.py", line 152, in open
    d = self.fn(url, self.options)
  File "C:\Users\brandon\python_virtualenvs\fedex_test\lib\site-packages\suds\wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "C:\Users\brandon\python_virtualenvs\fedex_test\lib\site-packages\suds\reader.py", line 79, in open
    d = self.download(url)
  File "C:\Users\brandon\python_virtualenvs\fedex_test\lib\site-packages\suds\reader.py", line 95, in download
    fp = self.options.transport.open(Request(url))
  File "C:\Users\brandon\python_virtualenvs\fedex_test\lib\site-packages\suds\transport\https.py", line 60, in open
    return  HttpTransport.open(self, request)
  File "C:\Users\brandon\python_virtualenvs\fedex_test\lib\site-packages\suds\transport\http.py", line 62, in open
    return self.u2open(u2request)
  File "C:\Users\brandon\python_virtualenvs\fedex_test\lib\site-packages\suds\transport\http.py", line 118, in u2open
    return url.open(u2request, timeout=tm)
  File "C:\Python27\Lib\urllib2.py", line 394, in open
    response = self._open(req, data)
  File "C:\Python27\Lib\urllib2.py", line 412, in _open
    '_open', req)
  File "C:\Python27\Lib\urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "C:\Python27\Lib\urllib2.py", line 1302, in file_open
    return self.open_local_file(req)
  File "C:\Python27\Lib\urllib2.py", line 1342, in open_local_file
    raise URLError(msg)
urllib2.URLError: <urlopen error [Error 3] The system cannot find the path specified: ''>

Any ideas on what could be the matter?

Thanks,
Brandon

**Comment by radlws** [comment]
Maybe you can leverage os.name to fix:

```
import os
if os.name == 'nt':
    pass # Windows
else:
    pass # other (unix)
```

http://stackoverflow.com/questions/4719063/can-python-detect-which-os-is-it-running-under

**Comment by gtaylor** [comment]
I'd welcome a pull request with something like this in it.

**Comment by gtaylor** [comment]
Going to close this. I'll definitely accept a PR, if anyone is interested in doing one.
